---
- hosts: all
  connection: local
  gather_facts: no
  tasks:
    - napalm_get_facts:
        hostname: "{{ inventory_hostname }}"
        username: "{{ user }}"
        password: "{{ pass }}"
        dev_os: "ios"
        filter: ['facts']
      register: napalm_facts
    - debug: msg="{{ napalm_facts.ansible_facts|to_nice_json }}"
